// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Sample NewsFeed API
This is a sample server for a News Feed.


    Schemes:
      http
    Host: localhost
    BasePath: /news-api/v1
    Version: 1.0.0
    Contact: NEWS API Support

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
