swagger: '2.0'
info:
  title: Sample NewsFeed API
  description: This is a sample server for a News Feed.
  contact:
    name: NEWS API Support
  version: 1.0.0
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /test:
    $ref: ./paths/test.yml
definitions:
  text-response:
    $ref: ./definitions/text-response.yml

basePath: /news-api/v1