// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Test test
// swagger:model test
type Test struct {
	TextResponse
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *Test) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 TextResponse
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.TextResponse = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m Test) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.TextResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this test
func (m *Test) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Test) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Test) UnmarshalBinary(b []byte) error {
	var res Test
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
